---
title: "Thyroid function"
date: '`r Sys.time()`'
output: 
  html_document: 
    toc: yes
    toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(kableExtra)
library(survival)
library(data.table)
library(flextable)
library(officer)
library(GGally)
library(survival)
library(htmltools)
library(dplyr)
library(corrplot)
library(RColorBrewer)
library(ggpubr)
knitr::opts_chunk$set(echo = FALSE)
setwd("/home/idiap/projects/scorewater/build.data")
load('conditions_standardized_byscensal.RData')
setDT(conditions_gral)
conditions_gral[is.na(conditions_gral)] <- NULL
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

# High prevalence -> Thyroid function
```{r}
data = conditions_gral[condicio == 'Thyroid function', keyby=.(scensal, provincia, condicio, stand.)]
data$poblacio_prevalent <- NULL
data$casos_prevalents <- NULL
data$casos_incidents <- NULL
data$poblacio_incident <- NULL
data1 <- data[order(data$stand., decreasing = TRUE), ]
data1 <- data1[1:10]
autofit(flextable(data1))
data1$scensal <- factor(data1$scensal, levels = data1$scensal)
ggplot() + 
  geom_bar(data = data1, aes(x=scensal, y=stand., fill = provincia), stat = 'identity') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, hjust = 1)) +
  ggtitle('10 regions with highest prevalence of Thyroid function') +
  labs(x = 'Censal code', y = 'Prevalence')
```

## Only Girona

```{r}
data1 = data[provincia == 'girona', keyby=.(scensal, provincia, condicio, stand.)]
data1 <- data1[order(data1$stand., decreasing = TRUE), ]
data1 <- data1[1:10]
autofit(flextable(data1))
data1$scensal <- factor(data1$scensal, levels = data1$scensal)
ggplot() + 
  geom_bar(data = data1, aes(x=scensal, y=stand., fill = provincia), stat = 'identity') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, hjust = 1)) +
  ggtitle('10 regions with highest prevalence of Thyroid function') +
  labs(x = 'Censal code', y = 'Prevalence')
```

# Low prevalence -> Thyroid function

```{r}
data1 <- data[order(data$stand., decreasing = FALSE), ]
data1 <- data1[1:10]
autofit(flextable(data1))
data1$scensal <- factor(data1$scensal, levels = data1$scensal)
ggplot() + 
  geom_bar(data = data1, aes(x=scensal, y=stand., fill = provincia), stat = 'identity') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, hjust = 1)) +
  ggtitle('10 regions with lowest prevalence of Thyroid function') +
  labs(x = 'Censal code', y = 'Prevalence')
```

## Only Girona

```{r}
data1 = data[provincia == 'girona', keyby=.(scensal, provincia, condicio, stand.)]
data1 <- data1[order(data1$stand., decreasing = FALSE), ]
data1 <- data1[1:10]
autofit(flextable(data1))
data1$scensal <- factor(data1$scensal, levels = data1$scensal)
ggplot() + 
  geom_bar(data = data1, aes(x=scensal, y=stand., fill = provincia), stat = 'identity') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, hjust = 1)) +
  ggtitle('10 regions with lowest prevalence of Thyroid function') +
  labs(x = 'Censal code', y = 'Prevalence')
```